### ISSUE TITLE
In Creating Our Class Mappings...

### ISSUE THREAD

**Issue by SoftwAIre** [learn-co-curriculum/dsc-2-13-10-using-an-orm-lab#1]
...we are instructed to create the correct table name: 'customer', 'shoppingCart', and 'Item'. the two previous table names start with a lowercase letter and the last table name, 'Item' starts with an uppercase i. Is it supposed to be like that? 

Thanks!

**Comment by PeterBell** [comment]
Fixed by @sik-flow - thanks @Chris-Manna !
